version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    environment:
      NODE_ENV: development
    ports:
      - '8081:8080'
    volumes:
      - .:/app
    working_dir: /app

  node:
    build: .
    tty: true
    volumes:
      - .:/work
    working_dir: /work

  db:
    image: mysql:5.7
    volumes:
      - ./volumes:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=typescript
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - 13306:3306
